### ISSUE TITLE
Multiple methods in multimethod 'simple-dispatch' match dispatch value

### ISSUE THREAD

**Issue by rrrnld** [thi-ng/color#10]
When trying out the library I received the following error:

```
Multiple methods in multimethod 'simple-dispatch' match dispatch value: class thi.ng.color.core.RGBA -> interface clojure.lang.IPersistentMap and interface clojure.lang.IDeref, and neither is preferred
```

This happend when trying to construct a color via `(col/css "string")` and `col/BLACK`.

Environment:
* Clojure version: 1.10.1.507
* CIDER 0.24.0 (package: 20200215.223) (India), nREPL 0.6.0

`deps.edn`:
```
{:deps {quil {:mvn/version "3.1.0"}
        thi.ng/geom {:mvn/version "1.0.0-RC4"}
        thi.ng/color {:mvn/version "1.4.0"}}}
```

**Comment by postspectacular** [comment]
Hmmm...  that seems to be a regression caused by Clojure 1.10.1 - I just tried in 1.9.0 and 1.10.0 and the error doesn't occur... will have to dig through Clojure changelog to see what they have changed about multi-method dispatch behavior...

**Comment by dimovich** [comment]
@heyarne When working at the REPL and printing the return values, you should use `deref`. Try this:

`@(col/css "#fff")`
`@col/BLACK`

This should also work fine (no deref needed):

`(def c (col/css "#fff"))`


Maybe @postspectacular could elaborate for this design decision. I think it's related to this:
https://github.com/thi-ng/color/blob/master/src/core.org#clojure-print-methods

**Comment by rrrnld** [comment]
You're right - derefing works fine. I don't know if this is
intentional, @postspectacular's comment makes it seem like it isn't.

-----Original Message-----

**Comment by postspectacular** [comment]
IMHO the issue is down to some Clojure internal changes (between 1.10.0 and 1.10.1) to the defmulti `print-method` and now impacts any `defrecord` which implements IDeref:

```clj
(defrecord Foo [x]
  clojure.lang.IDeref
  (deref [_] x))

(->Foo 42)
; Error printing return value (IllegalArgumentException) at clojure.lang.MultiFn/findAndCacheBestMethod (MultiFn.java:179).
; Multiple methods in multimethod 'print-method' match dispatch value: class user.Foo -> interface clojure.lang.IDeref and interface java.util.Map, and neither is preferred
```

I can fix the issue by adding manual preference hints for `print-method` via:

```clj
(prefer-method print-method clojure.lang.IRecord clojure.lang.IDeref)
(prefer-method print-method clojure.lang.IDeref java.util.Map)

(->Foo 42)
#user.Foo{:x 42}
```

The first of those is already implemented, but the second one is the new one seemingly needed... 

Thoughts? :)

**Comment by dimovich** [comment]
@postspectacular Your example works fine without using `prefer-method` as long as you require `thi.ng.color.core` first.

@heyarne I see that you're using CIDER. It defaults to using `clojure.pprint/pprint` as the printing function. [Here is the doc.](https://docs.cider.mx/cider/usage/pretty_printing.html)

That's why we're getting that error. We need to provide a `prefer-method` also for pprint. Here is some example code that will fix it:
https://github.com/Workiva/eva/blob/master/core/src/eva/v2/datastructures/var.clj#L34

I've tried running `(col/css "#fff")` at the terminal REPL (by running `clj`). It works fine for Clojure 1.9.0, 1.10.0 and 1.10.1. So we can safely assume that CIDER's preference for pprint is at fault here.

You can try running the following and check:

``` clojure
(require '[thi.ng.color.core :as col])

(prefer-method clojure.pprint/simple-dispatch clojure.lang.IPersistentMap clojure.lang.IDeref)

(col/css "#fff")
col/BLACK
```

**Comment by postspectacular** [comment]
@dimovich I'm not sure if your findings are 100% correct. I.e. I've been using `lein repl` with different clojure versions (1.9.0, 1.10.0, 1.10.1) and the issue only occurs w/ 1.10.1. I always require the core ns first (else couldn't test it anyhow)... maybe the lein repl (nrepl?) also does something extra compared to launching via `clj`... 

There's close to no documentation about how and where `print-method` and `pprint` work/are called from, so this all is partially "magic" to me and I remember the hours of trial and error getting this to work in the past...

**Comment by dimovich** [comment]
Some more investigation:

``` clojure
;; run in every scenario
(require '[thi.ng.color.core :as col])

(col/css "#fff")
```

**clj / Clojure 1.9 / 1.10 / 1.10.1**
``` clojure
; => #thi.ng.color.core.CSS{:col "#fff"}
```


**lein repl / Clojure 1.9.0**
``` clojure
; => #thi.ng.color.core.CSS{:col "#fff"}
```

**lein repl / Clojure 1.10.0**
``` clojure
; Error printing return value (IllegalArgumentException) at clojure.lang.MultiFn/findAndCacheBestMethod (MultiFn.java:179).
; Multiple methods in multimethod 'print-method' match dispatch value: class thi.ng.color.core.CSS -> interface clojure.lang.IDeref and interface java.util.Map, and neither is preferred
```

**lein repl / Clojure 1.10.1**
``` clojure
;; Error printing return value (IllegalArgumentException) at clojure.lang.MultiFn/findAndCacheBestMethod (MultiFn.java:179).
;; Multiple methods in multimethod 'print-method' match dispatch value: class thi.ng.color.core.CSS -> interface clojure.lang.IDeref and interface clojure.lang.IPersistentMap, and neither is preferred
```

**CIDER 0.24 / Clojure 1.9.0**
``` clojure
; IllegalArgumentException Multiple methods in multimethod 'simple-dispatch' match dispatch value: class thi.ng.color.core.CSS -> interface clojure.lang.IDeref and interface clojure.lang.IPersistentMap, and neither is preferred  clojure.lang.MultiFn.findAndCacheBestMethod (MultiFn.java:178)
```

**CIDER 0.24 / Clojure 1.10 / 1.10.1**
``` clojure
; Error printing return value (IllegalArgumentException) at clojure.lang.MultiFn/findAndCacheBestMethod (MultiFn.java:179).
; Multiple methods in multimethod 'simple-dispatch' match dispatch value: class thi.ng.color.core.CSS -> interface clojure.lang.IDeref and interface clojure.lang.IPersistentMap, and neither is preferred
```

To fix all of these we could run this:

``` clojure
;; fixes lein repl / Cloure 1.10.0 
(prefer-method print-method java.util.Map clojure.lang.IDeref)

;; fixes lein repl / Clojure 1.10.1
(prefer-method print-method clojure.lang.IPersistentMap clojure.lang.IDeref)

;; fixes CIDER / Clojure 1.9.0 / 1.10.0 / 1.10.1
(prefer-method clojure.pprint/simple-dispatch clojure.lang.IPersistentMap clojure.lang.IDeref)
```

After running this code we get the following results:

**lein repl / Clojure 1.9.0 / 1.10.0 / 1.10.1**
``` clojure
; => #thi.ng.color.core.CSS{:col "#fff"}
```

**CIDER / Clojure 1.9.0 / 1.10.0 / 1.10.1**
``` clojure
; => {:col "#fff"}
```

**Comment by postspectacular** [comment]
Thanks for the exhaustive testing @dimovich - you wanna send a PR? You can find the existing `prefer-method` call here:

https://github.com/thi-ng/color/blob/master/src/core.org#clojure-print-methods

**Comment by kxygk** [comment]
Could you make a new release @postspectacular ? :)
B/c of the orgmode setup this library can't be pulled directly from github with `deps.edn`

So this fails:
```
  thi.ng/color
  {:git/url
   "https://github.com/thi-ng/color.git"
   :git/sha
   "c7fe89306917512adbaee131657d4d578f2624a1"}}
```

**Comment by postspectacular** [comment]
@kxygk @heyarne @dimovich - please read here: https://twitter.com/thing_umbrella/status/1517881705285275648 :)

**Comment by kxygk** [comment]
@postspectacular  thank you so much. I know you've moved on to other projects, but I just want to thank you again for making thing/geom and company. I use it daily and it makes working with with SVG a ton of fun. It's also really easy to extend and modify when I need to.

It's been a really handy toolkit of sorts for making all my scientific presentations (maps/graphs/etc.)

**Comment by fkretlow** [comment]
Could you update the README so it points us to version 1.5.0? I ran into this issue because it still points to 1.4.0.
